# [supervisord]
# nodaemon=true

# [program:flask]
# directory=/app/src
# command=gunicorn -w 1 -b 0.0.0.0:5000 app:app
# autostart=true
# autorestart=true
# stdout_logfile=/var/log/flask.log
# stderr_logfile=/var/log/flask_err.log
# stdout_logfile_maxbytes=50MB 
# stderr_logfile_maxbytes=50MB 

# [program:nginx]
# command=/usr/sbin/nginx -g "daemon off;"
# autostart=true
# autorestart=true
# stdout_logfile=/var/log/nginx.log
# stderr_logfile=/var/log/nginx_err.log
# stdout_logfile_maxbytes=50MB 
# stderr_logfile_maxbytes=50MB 